# Generated by Django 4.1.2 on 2022-10-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('account_role', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
