# Generated by Django 4.1.2 on 2022-10-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.ForeignKey(default='Individual', on_delete=django.db.models.deletion.CASCADE, to='accounts.accountrole'),
            preserve_default=False,
        ),
    ]
