# Generated by Django 4.1.2 on 2022-10-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='role',
            new_name='account_role',
        ),
    ]
