# Generated by Django 4.1.2 on 2022-10-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('delay', models.DateField()),
                ('picture', models.ImageField(default='images/default.png', upload_to='images/')),
                ('beneficiary', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articletype')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
