# Generated by Django 4.1.2 on 2022-10-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='address',
        ),
        migrations.RemoveField(
            model_name='article',
            name='country',
        ),
    ]
